CREATE DATABASE IF NOT EXISTS `pugchat_multimedia_db`;
USE `pugchat_multimedia_db`;

CREATE TABLE IF NOT EXISTS archivos(
	`id` BIGINT PRIMARY KEY NOT NULL,
	`userid` BIGINT NOT NULL,
	`name` VARCHAR(256) NOT NULL,
	`link` VARCHAR(256) NOT NULL,
	`chatid` VARCHAR(256) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tags(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(256) NOT NULL UNIQUE,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS entries_tags(
	`id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`entry_id` BIGINT NOT NULL,
	`tag_id` BIGINT NOT NULL,

	CONSTRAINT fk_tag_id
    FOREIGN KEY (tag_id) 
    REFERENCES tags (id)
    ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_entry_id
    FOREIGN KEY (entry_id) 
    REFERENCES entries (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;
